import {Inter} from 'next/font/google'
import "./globals.css";
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { shadcn } from '@clerk/themes'


const inter = Inter({
  subsets:["latin"]
})

export const metadata = {
  title: "EcoEats : AI Recipes Platform",
  description: "Generated by jay1535",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      theme: shadcn,
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      ><Header/>
        <main className='min-h-screen'>
          
        {children}
        </main>
        <footer className='py-4 px-4 border-t'>
        <div className='max-w-6xl mx-auto flex justify-center items-center'>
          <p className='text-stone-500 text-sm'>
          Made with 💖 by jay1535
          </p>
          </div>
        </footer>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
