import {Inter} from 'next/font/google'
import "./globals.css";
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { shadcn } from '@clerk/themes'
import Footer from '@/components/Footer';


const inter = Inter({
  subsets:["latin"]
})

export const metadata = {
  title: "Servd : AI Recipes Platform",
  description: "Generated by jay1535",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      theme: shadcn,
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      ><Header/>
        <main className='min-h-screen'>
          
        {children}
        </main>
       <Footer/>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
